# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='measurement date')),
                ('temp', models.FloatField(verbose_name='temperature')),
                ('airHumidity', models.FloatField(verbose_name='air humidity')),
                ('soilHumidity', models.FloatField(verbose_name='soil humidity')),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('plantId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='watering date')),
                ('amount', models.FloatField(verbose_name='amount in liters')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_cultivation_statistics.Plants')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_cultivation_statistics.Plants'),
        ),
    ]
