# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='airHumidity',
            new_name='air_humidity',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='soilHumidity',
            new_name='soil_humidity',
        ),
    ]
