# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_plantsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='stats.Plant'),
        ),
        migrations.AlterField(
            model_name='watering',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterings', to='stats.Plant'),
        ),
    ]
