# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 18:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20160419_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantsettings',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='air_humidity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='air humidity'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(verbose_name='measurement date'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='soil_humidity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='soil humidity'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='plantsettings',
            name='mode',
            field=models.CharField(choices=[('t', 'Czasowo'), ('h', 'Na podstawie wilgotności'), ('d', 'Wyłącz')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='watering',
            name='amount',
            field=models.IntegerField(verbose_name='amount in milliliters'),
        ),
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateTimeField(verbose_name='watering date'),
        ),
    ]
