# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20160419_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantsettings',
            name='amount',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='watering date'),
        ),
    ]
