# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:05
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20160419_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='air_humidity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name=b'wilgotno\xc5\x9b\xc4\x87 powietrza'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(verbose_name=b'data pomiaru'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='soil_humidity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name=b'wilgotno\xc5\x9b\xc4\x87 gleby'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(verbose_name=b'temperatura'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=150, verbose_name=b'nazwa'),
        ),
        migrations.AlterField(
            model_name='plantsettings',
            name='amount',
            field=models.IntegerField(default=0, verbose_name=b'ilo\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='plantsettings',
            name='mode',
            field=models.CharField(choices=[(b't', b'Co okre\xc5\x9blony czas'), (b'h', b'Na podstawie wilgotno\xc5\x9bci'), (b'd', b'Dezaktywuj automatyczne podlewanie')], default=b'd', max_length=1, verbose_name=b'tryb'),
        ),
        migrations.AlterField(
            model_name='plantsettings',
            name='value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'warto\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='watering',
            name='amount',
            field=models.IntegerField(verbose_name=b'ilo\xc5\x9b\xc4\x87 w mililitrach'),
        ),
        migrations.AlterField(
            model_name='watering',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'data podlania'),
        ),
    ]
