# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 14:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20160423_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='insolation',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name=b'nas\xc5\x82onecznienie'),
        ),
    ]
